#!/usr/bin/env python3
"""
Generate GraphQL Resolvers

Scaffolds GraphQL resolvers following Clean Architecture.
Generates schema, resolver implementations, and integration with existing services.

Usage:
    python generate_graphql_resolvers.py --feature <feature_name> [--output <dir>]

Generated Files:
    - graphql/schema.graphql           - GraphQL schema definition
    - graphql/resolver.go              - Resolver implementations
    - graphql/types.go                 - GraphQL type definitions

Tech Stack:
    - gqlgen for code generation
    - Integration with existing services

Author: Expert Go Backend Developer Skill
"""

import argparse
import os
import sys
from pathlib import Path
from datetime import datetime


GRAPHQL_SCHEMA_TEMPLATE = '''# {FeatureName} GraphQL Schema
# Generated by Expert Go Backend Developer Skill

extend type Query {{
    "Get {entity} by ID"
    {entity}(id: ID!, tenantId: String!): {Entity}

    "List {entities} with pagination and filtering"
    {entityPlural}(
        tenantId: String!
        page: Int = 1
        pageSize: Int = 20
        filter: {Entity}FilterInput
    ): {Entity}Connection!

    "Search {entities}"
    search{EntityPlural}(
        tenantId: String!
        query: String!
        page: Int = 1
        pageSize: Int = 20
    ): {Entity}Connection!
}}

extend type Mutation {{
    "Create a new {entity}"
    create{Entity}(input: Create{Entity}Input!): {Entity}!

    "Update an existing {entity}"
    update{Entity}(id: ID!, input: Update{Entity}Input!): {Entity}!

    "Delete {entity}"
    delete{Entity}(id: ID!, tenantId: String!): Boolean!

    "Bulk delete {entities}"
    bulkDelete{EntityPlural}(ids: [ID!]!, tenantId: String!): BulkDeleteResult!
}}

# Types

type {Entity} {{
    id: ID!
    tenantId: String!
    name: String!
    description: String
    metadata: [MetadataEntry!]
    createdAt: DateTime!
    updatedAt: DateTime!
    createdBy: User
    updatedBy: User
}}

type MetadataEntry {{
    key: String!
    value: String!
}}

type {Entity}Connection {{
    items: [{Entity}!]!
    totalCount: Int!
    page: Int!
    pageSize: Int!
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
}}

type BulkDeleteResult {{
    success: Boolean!
    deletedCount: Int!
    failedIds: [ID!]
}}

# Inputs

input {Entity}FilterInput {{
    name: StringFilterInput
    description: StringFilterInput
    createdAt: DateRangeInput
    updatedAt: DateRangeInput
}}

input Create{Entity}Input {{
    tenantId: String!
    name: String!
    description: String
    metadata: [MetadataEntryInput!]
}}

input Update{Entity}Input {{
    name: String
    description: String
    metadata: [MetadataEntryInput!]
}}

input MetadataEntryInput {{
    key: String!
    value: String!
}}

input StringFilterInput {{
    eq: String
    contains: String
    startsWith: String
    endsWith: String
    in: [String!]
}}

input DateRangeInput {{
    from: DateTime
    to: DateTime
}}

# Scalars

scalar DateTime
'''

GRAPHQL_RESOLVER_TEMPLATE = '''package graphql

import (
    "context"
    "fmt"
    "time"

    "github.com/99designs/gqlgen/graphql"
    "github.com/vektah/gqlparser/v2/gqlerror"

    "{module}/features/{feature}/services"
    "{module}/utils/logging"
)

// Resolver handles GraphQL operations for {FeatureName}
type Resolver struct {{
    service services.{Entity}ServiceInterface
}}

// NewResolver creates a new GraphQL resolver
func NewResolver(service services.{Entity}ServiceInterface) *Resolver {{
    return &Resolver{{service: service}}
}}

// Query resolvers

func (r *queryResolver) {Entity}(ctx context.Context, id string, tenantID string) (*{Entity}, error) {{
    logger.Info("GraphQL {entity} query", "id", id, "tenant_id", tenantID)

    entity, err := r.service.GetByID(ctx, id, tenantID)
    if err != nil {{
        return nil, mapErrorToGraphQL(err)
    }}

    return toGraphQL{Entity}(entity), nil
}}

func (r *queryResolver) {EntityPlural}(ctx context.Context, tenantID string, page *int, pageSize *int, filter *{Entity}FilterInput) (*{Entity}Connection, error) {{
    logger.Info("GraphQL {entityPlural} query", "tenant_id", tenantID)

    p := page != nil && *page > 0
    ps := pageSize != nil && *pageSize > 0
    pageNum := 1
    pageSizeNum := 20

    if p {{
        pageNum = *page
    }}
    if ps {{
        pageSizeNum = *pageSize
    }}

    params := &services.ListParams{{
        TenantID: tenantID,
        Page:     pageNum,
        PageSize: pageSizeNum,
    }}

    if filter != nil {{
        params.Filter = mapFilterToDomain(filter)
    }}

    entities, total, err := r.service.List(ctx, params)
    if err != nil {{
        return nil, mapErrorToGraphQL(err)
    }}

    items := make([]*{Entity}, len(entities))
    for i, entity := range entities {{
        items[i] = toGraphQL{Entity}(entity)
    }}

    return &{Entity}Connection{{
        Items:       items,
        TotalCount:  total,
        Page:        pageNum,
        PageSize:    pageSizeNum,
        HasNextPage: total > pageNum*pageSizeNum,
        HasPreviousPage: pageNum > 1,
    }}, nil
}}

func (r *queryResolver) Search{EntityPlural}(ctx context.Context, tenantID string, query string, page *int, pageSize *int) (*{Entity}Connection, error) {{
    logger.Info("GraphQL search{entityPlural}", "tenant_id", tenantID, "query", query)

    // Implement search using the service
    params := &services.SearchParams{{
        TenantID: tenantID,
        Query:    query,
        Page:     getValue(page, 1),
        PageSize: getValue(pageSize, 20),
    }}

    entities, total, err := r.service.Search(ctx, params)
    if err != nil {{
        return nil, mapErrorToGraphQL(err)
    }}

    items := make([]*{Entity}, len(entities))
    for i, entity := range entities {{
        items[i] = toGraphQL{Entity}(entity)
    }}

    return &{Entity}Connection{{
        Items:       items,
        TotalCount:  total,
        Page:        params.Page,
        PageSize:    params.PageSize,
        HasNextPage: total > params.Page*params.PageSize,
        HasPreviousPage: params.Page > 1,
    }}, nil
}}

// Mutation resolvers

func (r *mutationResolver) Create{Entity}(ctx context.Context, input Create{Entity}Input) (*{Entity}, error) {{
    logger.Info("GraphQL create{Entity}", "tenant_id", input.TenantID)

    // Get user from context
    userID, _ := ctx.Value("user_id").(string)

    domainInput := &services.Create{Entity}Input{{
        TenantID:    input.TenantID,
        Name:        input.Name,
        Description: input.Description,
        Metadata:    mapMetadataToDomain(input.Metadata),
        CreatedBy:   userID,
    }}

    entity, err := r.service.Create(ctx, domainInput)
    if err != nil {{
        return nil, mapErrorToGraphQL(err)
    }}

    return toGraphQL{Entity}(entity), nil
}}

func (r *mutationResolver) Update{Entity}(ctx context.Context, id string, input Update{Entity}Input) (*{Entity}, error) {{
    logger.Info("GraphQL update{Entity}", "id", id)

    userID, _ := ctx.Value("user_id").(string)
    tenantID, _ := ctx.Value("tenant_id").(string)

    domainInput := &services.Update{Entity}Input{{
        ID:          id,
        TenantID:    tenantID,
        Name:        input.Name,
        Description: input.Description,
        Metadata:    mapMetadataToDomain(input.Metadata),
        UpdatedBy:   userID,
    }}

    entity, err := r.service.Update(ctx, domainInput)
    if err != nil {{
        return nil, mapErrorToGraphQL(err)
    }}

    return toGraphQL{Entity}(entity), nil
}}

func (r *mutationResolver) Delete{Entity}(ctx context.Context, id string, tenantID string) (bool, error) {{
    logger.Info("GraphQL delete{Entity}", "id", id, "tenant_id", tenantID)

    if err := r.service.Delete(ctx, id, tenantID); err != nil {{
        return false, mapErrorToGraphQL(err)
    }}

    return true, nil
}}

func (r *mutationResolver) BulkDelete{EntityPlural}(ctx context.Context, ids []string, tenantID string) (*BulkDeleteResult, error) {{
    logger.Info("GraphQL bulkDelete{EntityPlural}", "ids_count", len(ids), "tenant_id", tenantID)

    deletedCount, failedIDs, err := r.service.BulkDelete(ctx, ids, tenantID)
    if err != nil {{
        return nil, mapErrorToGraphQL(err)
    }}

    return &BulkDeleteResult{{
        Success:      deletedCount > 0,
        DeletedCount: deletedCount,
        FailedIDs:    failedIDs,
    }}, nil
}}

// Helper functions

func toGraphQL{Entity}(entity *services.{Entity}) *{Entity} {{
    if entity == nil {{
        return nil
    }}

    metadata := make([]*MetadataEntry, 0, len(entity.Metadata))
    for k, v := range entity.Metadata {{
        metadata = append(metadata, &MetadataEntry{{Key: k, Value: v}})
    }}

    return &{Entity}{{
        ID:          entity.ID,
        TenantID:    entity.TenantID,
        Name:        entity.Name,
        Description: &entity.Description,
        Metadata:    metadata,
        CreatedAt:   entity.CreatedAt,
        UpdatedAt:   entity.UpdatedAt,
    }}
}}

func mapErrorToGraphQL(err error) error {{
    if errors.Is(err, services.ErrEntityNotFound) {{
        return gqlerror.Errorf("not found")
    }}
    if errors.Is(err, services.ErrInvalidInput) {{
        return gqlerror.Errorf("invalid input: %v", err)
    }}
    if errors.Is(err, services.ErrDuplicate) {{
        return gqlerror.Errorf("already exists")
    }}
    return gqlerror.Errorf("internal error: %v", err)
}}

func getValue[T any](ptr *T, defaultVal T) T {{
    if ptr == nil {{
        return defaultVal
    }}
    return *ptr
}}
'''

GRAPHQL_TYPES_TEMPLATE = '''package graphql

import (
    "time"
)

// GraphQL Types

type {Entity} struct {{
    ID          string          `json:"id"`
    TenantID    string          `json:"tenantId"`
    Name        string          `json:"name"`
    Description *string         `json:"description"`
    Metadata    []*MetadataEntry `json:"metadata"`
    CreatedAt   time.Time       `json:"createdAt"`
    UpdatedAt   time.Time       `json:"updatedAt"`
    CreatedBy   *User           `json:"createdBy"`
    UpdatedBy   *User           `json:"updatedBy"`
}}

type MetadataEntry struct {{
    Key   string `json:"key"`
    Value string `json:"value"`
}}

type User struct {{
    ID    string  `json:"id"`
    Name  string  `json:"name"`
    Email string  `json:"email"`
}}

type {Entity}Connection struct {{
    Items          []*{Entity} `json:"items"`
    TotalCount     int         `json:"totalCount"`
    Page           int         `json:"page"`
    PageSize       int         `json:"pageSize"`
    HasNextPage    bool        `json:"hasNextPage"`
    HasPreviousPage bool       `json:"hasPreviousPage"`
}}

type BulkDeleteResult struct {{
    Success      bool     `json:"success"`
    DeletedCount int      `json:"deletedCount"`
    FailedIDs    []string `json:"failedIds"`
}}

// Input Types

type {Entity}FilterInput struct {{
    Name        *StringFilterInput `json:"name"`
    Description *StringFilterInput `json:"description"`
    CreatedAt   *DateRangeInput    `json:"createdAt"`
    UpdatedAt   *DateRangeInput    `json:"updatedAt"`
}}

type Create{Entity}Input struct {{
    TenantID    string              `json:"tenantId"`
    Name        string              `json:"name"`
    Description *string             `json:"description"`
    Metadata    []*MetadataEntryInput `json:"metadata"`
}}

type Update{Entity}Input struct {{
    Name        *string             `json:"name"`
    Description *string             `json:"description"`
    Metadata    []*MetadataEntryInput `json:"metadata"`
}}

type MetadataEntryInput struct {{
    Key   string `json:"key"`
    Value string `json:"value"`
}}

type StringFilterInput struct {{
    EQ        *string   `json:"eq"`
    Contains  *string   `json:"contains"`
    StartsWith *string  `json:"startsWith"`
    EndsWith   *string  `json:"endsWith"`
    In        []string  `json:"in"`
}}

type DateRangeInput struct {{
    From *time.Time `json:"from"`
    To   *time.Time `json:"to"`
}}
'''

GQLGEN_CONFIG_TEMPLATE = '''# gqlgen configuration
schema:
  - graphql/schema.graphql

exec:
  filename: graphql/generated.go
  package: graphql

model:
  filename: graphql/models_gen.go
  package: graphql

resolver:
  filename: graphql/resolver.go
  package: graphql
  type: Resolver

autobind:
  - "{module}/graphql"

models:
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
  ID:
    model: github.com/99designs/gqlgen/graphql.ID
'''


def generate_graphql_resolvers(feature: str, module: str, output_dir: Path) -> dict:
    """Generate GraphQL resolver files for a feature."""
    feature_lower = feature.lower()
    feature_camel = ''.join(word.capitalize() for word in feature.split('_'))
    entity_camel = feature_camel
    entity_plural = feature_camel + "s"  # Simple pluralization

    replacements = {
        '{feature}': feature_lower,
        '{FeatureName}': feature_camel,
        '{Entity}': entity_camel,
        '{entity}': feature_lower,
        '{EntityPlural}': entity_plural,
        '{entityPlural}': feature_lower + 's',
        '{module}': module,
    }

    files_created = []

    # Create graphql directory
    graphql_dir = output_dir / 'graphql'
    graphql_dir.mkdir(parents=True, exist_ok=True)

    # Generate schema
    schema_content = GRAPHQL_SCHEMA_TEMPLATE
    for key, value in replacements.items():
        schema_content = schema_content.replace(key, value)
    schema_file = graphql_dir / 'schema.graphql'
    schema_file.write_text(schema_content)
    files_created.append(str(schema_file))

    # Generate resolver
    resolver_content = GRAPHQL_RESOLVER_TEMPLATE
    for key, value in replacements.items():
        resolver_content = resolver_content.replace(key, value)
    resolver_file = graphql_dir / 'resolver.go'
    resolver_file.write_text(resolver_content)
    files_created.append(str(resolver_file))

    # Generate types
    types_content = GRAPHQL_TYPES_TEMPLATE
    for key, value in replacements.items():
        types_content = types_content.replace(key, value)
    types_file = graphql_dir / 'types.go'
    types_file.write_text(types_content)
    files_created.append(str(types_file))

    # Generate gqlgen config
    config_content = GQLGEN_CONFIG_TEMPLATE
    for key, value in replacements.items():
        config_content = config_content.replace(key, value)
    config_file = output_dir / 'gqlgen.yml'
    config_file.write_text(config_content)
    files_created.append(str(config_file))

    return {
        'feature': feature,
        'files': files_created,
        'commands': {
            'generate': f'cd {output_dir} && go run github.com/99designs/gqlgen generate',
            'install': 'go get github.com/99designs/gqlgen/graphql',
        }
    }


def main():
    parser = argparse.ArgumentParser(
        description='Generate GraphQL resolvers'
    )
    parser.add_argument(
        '--feature',
        required=True,
        help='Feature name (e.g., workflow, vehicle_management)'
    )
    parser.add_argument(
        '--module',
        default='github.com/av-platform',
        help='Go module path'
    )
    parser.add_argument(
        '--output',
        default='features',
        help='Output directory (default: features)'
    )

    args = parser.parse_args()
    output_dir = Path(args.output) / args.feature.lower()

    result = generate_graphql_resolvers(args.feature, args.module, output_dir)

    print(f"\n✅ GraphQL Resolvers generated for '{args.feature}'")
    print(f"\n📁 Files created:")
    for f in result['files']:
        print(f"   - {f}")

    print(f"\n🔧 Next steps:")
    print(f"   1. Install gqlgen:")
    print(f"      {result['commands']['install']}")
    print(f"   2. Generate code:")
    print(f"      {result['commands']['generate']}")
    print(f"   3. Implement business logic in services/")
    print(f"   4. Register resolver in GraphQL server")


if __name__ == "__main__":
    main()
